#!/bin/bash

# https://wiki.ubuntu.com/ReducingDiskFootprint
# https://wiki.debian.org/ReduceDebian

## Creates a tiny baseline for debian11
#    sh -c "$(curl -fsSL http://<server>/shrink-debian11)"

# Also - see: https://wiki.debian.org/ReduceDebian#Remove_non-critical_packages

apt purge vim-* postfix man-db x11-common libx11* xauth libvulkan1 reportbug libgl1 bind9* mime-support libxft2 apt-listchanges \
  python3-reportbug doc-debian locales tasksel* netcat* wamerican perl python* debian-faq krb5-locales media-types libmagic* libdrm*


 #  dpkg-query -Wf '${Package;-40}${Priority}\n' | sort -b -k2,2 -k1,1 | grep -v required | grep -v important
# Before:
# ~ 26mb ram
# 20.0% 570.4M      3.1G   3.9G /

# apt-get clean
# 18.5% 509.3M      3.1G   3.9G /

# rm -rf /var/lib/apt/lists/*
# 17.3% 464.7M      3.2G   3.9G /

apt purge bind9-host            # dig, nslookup, nsupdate
apt purge debian-faq*
apt purge doc-debian
apt purge file
apt purge dnsutils
apt purge gettext-base
apt purge groff*
apt purge manpages
apt purge reportbug
apt purge tasksel*
apt purge traceroute
apt purge vim-*
apt purge wamerican
apt purge postfix
apt purge file
apt purge udev
apt purge telnet
apt purge bind9*
apt purge krb5-locales
apt purge telnet
apt purge python3-reportbug
apt purge libmagic*
apt purge cpio
apt purge dmidecode
apt purge xxd
apt purge libicu*  # ??
apt purge apt-listchanges
apt purge fdisk
apt purge bzip2
apt purge media-types # ??
apt purge lsof
apt purge nftables
apt purge libnftables1
apt purge libfdisk1
apt purge libmaxminddb0


cat > /etc/apt/apt.conf.d/99custom <<"EOF"
Acquire::CompressionTypes::Order:: "gz";
Acquire::GzipIndexes "true";
Acquire::IndexTargets::deb-src::Sources::KeepCompressedAs "gz";
Acquire::IndexTargets::deb::Packages::KeepCompressedAs "gz";
Acquire::IndexTargets::deb::Translations::KeepCompressedAs "gz";
Acquire::Languages "none";
APT::AutoRemove::RecommendsImportant "false";
APT::AutoRemove::SuggestsImportant "false";
APT::Install-Recommends "false";
APT::Install-Suggests "false";
EOF
#Dir::Cache {
#   srcpkgcache "";
#   pkgcache "";
# }


# https://sleeplessbeastie.eu/2018/09/03/how-to-remove-useless-localizations/
apt install localepurge

rm -rI /usr/share/locale/!(en) # TODO: Also keep locale.alias
rm -rfv /usr/share/man/*
rm -rfv /usr/share/doc/*
rm /var/cache/apt/*.bin
dpkg --clear-avail
apt-get autoremove
apt-get clean

# Disable imklog (causing systemd to become a degraded status)
sed -i '/imklog/s/^/#/' /etc/rsyslog.conf

systemctl disable systemd-pstore.service
systemctl disable remote-fs.target
systemctl disable fstrim.timer
systemctl disable e2scrub_reap.service
systemctl disable e2scrub_all.timer

#systemctl mask serial-getty@.service
#systemctl mask container-getty@1.service
#systemctl mask container-getty@2.service
systemctl mask systemd-journald-audit.socket
systemctl mask sys-kernel-config.mount

# bsdextrautils                           optional
# dfc                                     optional
# distro-info-data                        optional
# dmsetup                                 optional
# htop                                    optional
# libacl1                                 optional
# libapparmor1                            optional
# libapt-pkg6.0                           optional
# libargon2-1                             optional
# libattr1                                optional
# libaudit-common                         optional
# libaudit1                               optional
# libblkid1                               optional
# libbpf0                                 optional
# libbrotli1                              optional
# libbsd0                                 optional
# libbz2-1.0                              optional
# libc6                                   optional
# libcap-ng0                              optional
# libcap2                                 optional
# libcap2-bin                             optional
# libcbor0                                optional
# libcom-err2                             optional
# libcrypt1                               optional
# libcryptsetup12                         optional
# libcurl3-gnutls                         optional
# libdb5.3                                optional
# libdbus-1-3                             optional
# libdebconfclient0                       optional
# libdevmapper1.02.1                      optional
# libdns-export1110                       optional
# libedit2                                optional
# libelf1                                 optional
# libestr0                                optional
# libexpat1                               optional
# libext2fs2                              optional
# libfastjson4                            optional
# libfdisk1                               optional
# libffi7                                 optional
# libfido2-1                              optional
# libfstrm0                               optional
# libgcc-s1                               optional
# libgcrypt20                             optional
# libgdbm-compat4                         optional
# libgdbm6                                optional
# libgmp10                                optional
# libgnutls30                             optional
# libgpg-error0                           optional
# libgssapi-krb5-2                        optional
# libhogweed6                             optional
# libicu67                                optional
# libidn2-0                               optional
# libip4tc2                               optional
# libisc-export1105                       optional
# libjansson4                             optional
# libjson-c5                              optional
# libk5crypto3                            optional
# libkeyutils1                            optional
# libkmod2                                optional
# libkrb5-3                               optional
# libkrb5support0                         optional
# libldap-2.4-2                           optional
# liblmdb0                                optional
# liblocale-gettext-perl                  optional
# liblognorm5                             optional
# liblz4-1                                optional
# liblzma5                                optional
# libmaxminddb0                           optional
# libmd0                                  optional
# libmnl0                                 optional
# libmount1                               optional
# libmpdec3                               optional
# libncurses6                             optional
# libncursesw6                            optional
# libnettle8                              optional
# libnewt0.52                             optional
# libnftables1                            optional
# libnftnl11                              optional
# libnghttp2-14                           optional
# libnl-3-200                             optional
# libnl-genl-3-200                        optional
# libnsl2                                 optional
# libp11-kit0                             optional
# libpam0g                                optional
# libpcre2-8-0                            optional
# libpcre3                                optional
# libperl5.32                             optional
# libpipeline1                            optional
# libpopt0                                optional
# libprocps8                              optional
# libprotobuf-c1                          optional
# libpsl5                                 optional
# libpython3-stdlib                       optional
# libpython3.9-minimal                    optional
# libpython3.9-stdlib                     optional
# librtmp1                                optional
# libsasl2-2                              optional
# libsasl2-modules-db                     optional
# libseccomp2                             optional
# libselinux1                             optional
# libsemanage-common                      optional
# libsemanage1                            optional
# libsepol1                               optional
# libslang2                               optional
# libsmartcols1                           optional
# libsqlite3-0                            optional
# libss2                                  optional
# libssh2-1                               optional
# libssl1.1                               optional
# libstdc++6                              optional
# libsystemd0                             optional
# libtasn1-6                              optional
# libtext-charwidth-perl                  optional
# libtext-iconv-perl                      optional
# libtext-wrapi18n-perl                   optional
# libtinfo6                               optional
# libtirpc-common                         optional
# libtirpc3                               optional
# libuchardet0                            optional
# libudev1                                optional
# libunistring2                           optional
# libuuid1                                optional
# libuv1                                  optional
# libwrap0                                optional
# libxml2                                 optional
# libxtables12                            optional
# libxxhash0                              optional
# libzstd1                                optional
# localepurge                             optional
# logsave                                 optional
# lsb-base                                optional
# mailcap                                 optional
# ncdu                                    optional
# openssh-server                          optional
# openssh-sftp-server                     optional
# openssl                                 optional
# python-apt-common                       optional
# python3                                 optional
# python3-apt                             optional
# python3-certifi                         optional
# python3-chardet                         optional
# python3-debconf                         optional
# python3-debian                          optional
# python3-debianbts                       optional
# python3-httplib2                        optional
# python3-idna                            optional
# python3-minimal                         optional
# python3-pkg-resources                   optional
# python3-pycurl                          optional
# python3-pysimplesoap                    optional
# python3-requests                        optional
# python3-six                             optional
# python3-urllib3                         optional
# python3.9                               optional
# python3.9-minimal                       optional
# runit-helper                            optional
# ssh                                     optional
# ssl-cert                                optional
# xxd                                     optional
# zlib1g                                  optional
# apt-listchanges                         standard
# bash-completion                         standard
# bzip2                                   standard
# ca-certificates                         standard
# dbus                                    standard
# libc-l10n                               standard
# liblockfile-bin                         standard
# libnss-systemd                          standard
# libpam-systemd                          standard
# locales                                 standard
# lsof                                    standard
# media-types                             standard
# mime-support                            standard
# ncurses-term                            standard
# netcat-traditional                      standard
# openssh-client                          standard
# perl                                    standard
# perl-modules-5.32                       standard
# systemd-timesyncd                       standard
# ucf                                     standard
# wget                                    standard
# xz-utils                                standard
